import json
import os

def create_notebook(filename, cells):
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)
    print(f"Created {filename}")

def markdown_cell(source_lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source_lines]
    }

def code_cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source_lines]
    }

# ----------------- Notebook 1: Linear Algebra -----------------
la_cells = [
    markdown_cell([
        "# ML Mathematics Playground: 01. Linear Algebra",
        "",
        "Linear Algebra is the absolute foundation of Machine Learning and AI. Every dataset is a matrix, every model parameter is a vector weight, and every layer transformation is matrix multiplication.",
        "",
        "In this notebook, we will explore:",
        "1. **Vector Operations** (Geometric view of addition & scaling)",
        "2. **Linear Transformations** (Deforming 2D space with matrices)",
        "3. **Eigenvalues & Eigenvectors** (Directions that remain invariant under transformations)",
        "",
        "Let's import our libraries and set up the interactive widgets."
    ]),
    code_cell([
        "%matplotlib inline",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "import ipywidgets as widgets",
        "from ipywidgets import interact, interactive",
        "",
        "# Set clean style",
        "plt.style.use('ggplot')",
        "plt.rcParams['figure.figsize'] = (6, 6)"
    ]),
    markdown_cell([
        "## Section 1: Vector Operations",
        "",
        "A vector can be represented as coordinates $[x, y]$ or geometrically as an arrow pointing from the origin $(0,0)$ to $(x, y)$.",
        "- **Addition ($\vec{u} + \vec{v}$)**: Placed 'tip-to-tail', representing combined movements.",
        "- **Scaling ($c\vec{u}$)**: Changes the length (magnitude) and/or direction (sign) of a vector.",
        "",
        "Use the sliders below to adjust the vectors $\vec{u}$ and $\vec{v}$ and see their sum $\vec{u} + \vec{v}$ dynamically."
    ]),
    code_cell([
        "def plot_vector_addition(ux, uy, vx, vy):",
        "    u = np.array([ux, uy])",
        "    v = np.array([vx, vy])",
        "    w = u + v",
        "    ",
        "    fig, ax = plt.subplots()",
        "    ",
        "    # Draw grid lines and origin axes",
        "    ax.axhline(0, color='grey', lw=1)",
        "    ax.axvline(0, color='grey', lw=1)",
        "    ",
        "    # Plot vectors",
        "    ax.quiver(0, 0, u[0], u[1], angles='xy', scale_units='xy', scale=1, color='#1f77b4', label=f'u = [{ux}, {uy}]')",
        "    ax.quiver(u[0], u[1], v[0], v[1], angles='xy', scale_units='xy', scale=1, color='#ff7f0e', label=f'v = [{vx}, {vy}] (tip-to-tail)')",
        "    ax.quiver(0, 0, w[0], w[1], angles='xy', scale_units='xy', scale=1, color='#2ca02c', label=f'u + v = [{w[0]}, {w[1]}]')",
        "    ",
        "    # Set limits and grid",
        "    limit = max(10, np.max(np.abs([u, v, w])) + 2)",
        "    ax.set_xlim(-limit, limit)",
        "    ax.set_ylim(-limit, limit)",
        "    ax.set_aspect('equal')",
        "    ax.grid(True, which='both', linestyle='--', alpha=0.5)",
        "    ax.legend(loc='upper left')",
        "    ax.set_title('Vector Addition & Scaling Playground')",
        "    plt.show()",
        "",
        "interact(plot_vector_addition,",
        "         ux=widgets.IntSlider(value=3, min=-10, max=10, step=1, description='u_x'),",
        "         uy=widgets.IntSlider(value=4, min=-10, max=10, step=1, description='u_y'),",
        "         vx=widgets.IntSlider(value=4, min=-10, max=10, step=1, description='v_x'),",
        "         vy=widgets.IntSlider(value=-2, min=-10, max=10, step=1, description='v_y'));"
    ]),
    markdown_cell([
        "## Section 2: Linear Transformations",
        "",
        "A matrix multiplication $A\vec{x}$ represents a **linear transformation** of space. The columns of the matrix $A$ define where the basis vectors $\hat{i} = [1, 0]^T$ and $\hat{j} = [0, 1]^T$ land after the transformation.",
        "",
        "Let's define a matrix:",
        "$$A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$$",
        "",
        "Use the sliders below to change $a, b, c, d$ and watch how the unit grid transforms. Notice how rotation, shearing, scaling, and reflection are achieved by choosing different values."
    ]),
    code_cell([
        "def plot_linear_transformation(a, b, c, d):",
        "    # Create a grid of points",
        "    x = np.linspace(-5, 5, 11)",
        "    y = np.linspace(-5, 5, 11)",
        "    xx, yy = np.meshgrid(x, y)",
        "    grid_points = np.vstack([xx.flatten(), yy.flatten()])",
        "    ",
        "    # Define Transformation Matrix",
        "    A = np.array([[a, b], [c, d]])",
        "    ",
        "    # Apply transformation",
        "    transformed_points = A @ grid_points",
        "    ",
        "    # Separate x and y",
        "    tx = transformed_points[0].reshape(xx.shape)",
        "    ty = transformed_points[1].reshape(yy.shape)",
        "    ",
        "    fig, ax = plt.subplots(figsize=(7, 7))",
        "    ",
        "    # Plot original grid lines lightly",
        "    for i in range(xx.shape[0]):",
        "        ax.plot(xx[i, :], yy[i, :], color='lightblue', alpha=0.3, linestyle=':')",
        "        ax.plot(xx[:, i], yy[:, i], color='lightblue', alpha=0.3, linestyle=':')",
        "        ",
        "    # Plot transformed grid lines",
        "    for i in range(tx.shape[0]):",
        "        ax.plot(tx[i, :], ty[i, :], color='#1f77b4', alpha=0.7)",
        "        ax.plot(tx[:, i], ty[:, i], color='#1f77b4', alpha=0.7)",
        "        ",
        "    # Plot new basis vectors",
        "    ax.quiver(0, 0, a, c, angles='xy', scale_units='xy', scale=1, color='red', width=0.015, label='Transformed i-hat')",
        "    ax.quiver(0, 0, b, d, angles='xy', scale_units='xy', scale=1, color='green', width=0.015, label='Transformed j-hat')",
        "    ",
        "    ax.axhline(0, color='black', lw=0.8)",
        "    ax.axvline(0, color='black', lw=0.8)",
        "    ax.set_xlim(-10, 10)",
        "    ax.set_ylim(-10, 10)",
        "    ax.set_aspect('equal')",
        "    ax.grid(True, linestyle='--', alpha=0.5)",
        "    ax.legend(loc='upper left')",
        "    ax.set_title(f'Transformation Matrix A = [[{a}, {b}], [{c}, {d}]]')",
        "    plt.show()",
        "",
        "interact(plot_linear_transformation,",
        "         a=widgets.FloatSlider(value=1.0, min=-3.0, max=3.0, step=0.1, description='a (i_x)'),",
        "         b=widgets.FloatSlider(value=0.0, min=-3.0, max=3.0, step=0.1, description='b (j_x)'),",
        "         c=widgets.FloatSlider(value=0.0, min=-3.0, max=3.0, step=0.1, description='c (i_y)'),",
        "         d=widgets.FloatSlider(value=1.0, min=-3.0, max=3.0, step=0.1, description='d (j_y)'));"
    ]),
    markdown_cell([
        "## Section 3: Eigenvalues & Eigenvectors",
        "",
        "For a matrix $A$, eigenvectors $\vec{v}$ are vectors whose direction **does not change** when transformed by $A$. They are only scaled by a factor $\lambda$ (the eigenvalue):",
        "$$A\vec{v} = \lambda \vec{v}$$",
        "",
        "### Interactive Eigenvector Hunt!",
        "Below is a matrix $A = \\begin{pmatrix} 2 & 1 \\\\ 1 & 2 \\end{pmatrix}$.",
        "Use the slider to rotate an input vector $\vec{x}$ (red). Watch the output vector $A\vec{x}$ (blue).",
        "Can you find the angles where the red and blue vectors line up exactly? Those are the eigenvectors!"
    ]),
    code_cell([
        "# Fixed matrix",
        "A = np.array([[2.0, 1.0], [1.0, 2.0]])",
        "",
        "# Find actual eigenvectors for reference line display",
        "evals, evecs = np.linalg.eig(A)",
        "",
        "def hunt_eigenvectors(theta_deg):",
        "    theta = np.radians(theta_deg)",
        "    # Input vector",
        "    x = np.array([np.cos(theta), np.sin(theta)]) * 3",
        "    # Output vector",
        "    Ax = A @ x",
        "    ",
        "    fig, ax = plt.subplots(figsize=(6, 6))",
        "    ax.axhline(0, color='grey', lw=1)",
        "    ax.axvline(0, color='grey', lw=1)",
        "    ",
        "    # Plot input vector",
        "    ax.quiver(0, 0, x[0], x[1], angles='xy', scale_units='xy', scale=1, color='red', width=0.012, label='Input Vector x')",
        "    # Plot output vector",
        "    ax.quiver(0, 0, Ax[0], Ax[1], angles='xy', scale_units='xy', scale=1, color='blue', width=0.012, label='Output Vector Ax')",
        "    ",
        "    # Check if they are collinear (dot product test)",
        "    unit_x = x / np.linalg.norm(x)",
        "    unit_Ax = Ax / np.linalg.norm(Ax)",
        "    collinear = np.abs(np.dot(unit_x, unit_Ax)) > 0.999",
        "    ",
        "    if collinear:",
        "        lambda_approx = np.linalg.norm(Ax) / np.linalg.norm(x)",
        "        # check direction",
        "        if np.dot(unit_x, unit_Ax) < 0:",
        "            lambda_approx = -lambda_approx",
        "        ax.set_title(f'🎉 EIGENVECTOR FOUND! lambda ≈ {lambda_approx:.2f}', color='green', fontsize=14, fontweight='bold')",
        "    else:",
        "        ax.set_title('Rotate x to align with Ax')",
        "        ",
        "    ax.set_xlim(-10, 10)",
        "    ax.set_ylim(-10, 10)",
        "    ax.set_aspect('equal')",
        "    ax.grid(True, linestyle='--', alpha=0.5)",
        "    ax.legend(loc='upper left')",
        "    plt.show()",
        "",
        "interact(hunt_eigenvectors, theta_deg=widgets.IntSlider(value=0, min=0, max=360, step=5, description='Angle (deg)'));"
    ])
]

# ----------------- Notebook 2: Calculus & Optimization -----------------
calc_cells = [
    markdown_cell([
        "# ML Mathematics Playground: 02. Calculus & Optimization",
        "",
        "Optimization is the engine that allows AI models to learn. Gradient Descent uses calculus to iteratively adjust parameters (weights) to minimize error (loss).",
        "",
        "In this notebook, we will explore:",
        "1. **The Tangent Limit**: How derivatives measure slope.",
        "2. **1D Gradient Descent**: Minimizing cost functions dynamically.",
        "3. **3D Optimization Landscapes**: Visualizing partial derivatives and saddle points."
    ]),
    code_cell([
        "%matplotlib inline",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "import ipywidgets as widgets",
        "from ipywidgets import interact, interactive",
        "",
        "plt.style.use('ggplot')",
        "plt.rcParams['figure.figsize'] = (8, 5)"
    ]),
    markdown_cell([
        "## Section 1: The Tangent Limit",
        "",
        "The derivative of a function $f(x)$ at $x$ measures the instantaneous rate of change. It is defined as the limit of the secant line slope as $\Delta x \to 0$:",
        "$$f'(x) = \\lim_{\\Delta x \\to 0} \\frac{f(x + \\Delta x) - f(x)}{\\Delta x}$$",
        "",
        "Drag the $\\Delta x$ slider below to see the secant line approach the true tangent line for $f(x) = x^2$ at $x_0 = 2$."
    ]),
    code_cell([
        "def f(x):",
        "    return x**2",
        "",
        "def plot_tangent_limit(dx):",
        "    x0 = 2.0",
        "    y0 = f(x0)",
        "    ",
        "    x_vals = np.linspace(-1, 5, 200)",
        "    y_vals = f(x_vals)",
        "    ",
        "    fig, ax = plt.subplots()",
        "    ax.plot(x_vals, y_vals, label='f(x) = x^2', color='blue', lw=2)",
        "    ax.scatter([x0], [y0], color='red', s=100, zorder=5, label='Point (x0, y0)')",
        "    ",
        "    # Target point",
        "    x1 = x0 + dx",
        "    y1 = f(x1)",
        "    ax.scatter([x1], [y1], color='orange', s=80, zorder=5, label='x0 + dx')",
        "    ",
        "    # Secant line",
        "    slope = (y1 - y0) / dx if dx != 0 else 4.0",
        "    secant_y = slope * (x_vals - x0) + y0",
        "    ax.plot(x_vals, secant_y, '--', color='orange', label=f'Secant slope = {slope:.3f}')",
        "    ",
        "    # True tangent",
        "    true_slope = 4.0",
        "    tangent_y = true_slope * (x_vals - x0) + y0",
        "    ax.plot(x_vals, tangent_y, color='green', alpha=0.6, label='True Tangent slope = 4.000')",
        "    ",
        "    ax.set_ylim(-2, 25)",
        "    ax.grid(True, linestyle='--', alpha=0.5)",
        "    ax.legend()",
        "    ax.set_title(f'Approaching the Derivative (dx = {dx:.3f})')",
        "    plt.show()",
        "",
        "interact(plot_tangent_limit, dx=widgets.FloatSlider(value=2.0, min=0.01, max=3.0, step=0.05, description='dx'));"
    ]),
    markdown_cell([
        "## Section 2: 1D Gradient Descent Simulator",
        "",
        "To minimize a loss function, gradient descent updates $x$ using the rule:",
        "$$x_{new} = x_{old} - \\alpha \\cdot f'(x_{old})$$",
        "where $\\alpha$ is the **learning rate**.",
        "",
        "Let's test this on two functions:",
        "1. **Convex**: $f(x) = x^2$ (one clear minimum).",
        "2. **Non-Convex**: $f(x) = x^4 - 2x^2$ (multiple local minima).",
        "",
        "Change the learning rate $\\alpha$ and see what happens when it is too small (slow learning) or too large (exploding steps / oscillation)."
    ]),
    code_cell([
        "def g_convex(x):",
        "    return x**2",
        "def dg_convex(x):",
        "    return 2*x",
        "",
        "def g_nonconvex(x):",
        "    return x**4 - 2*x**2",
        "def dg_nonconvex(x):",
        "    return 4*x**3 - 4*x",
        "",
        "def simulate_gd(func_type, start_x, lr, steps):",
        "    if func_type == 'Convex (x^2)':",
        "        f, df = g_convex, dg_convex",
        "        x_range = np.linspace(-3, 3, 200)",
        "    else:",
        "        f, df = g_nonconvex, dg_nonconvex",
        "        x_range = np.linspace(-1.8, 1.8, 200)",
        "        ",
        "    # Run Gradient Descent",
        "    history_x = [start_x]",
        "    history_y = [f(start_x)]",
        "    curr_x = start_x",
        "    for _ in range(steps):",
        "        grad = df(curr_x)",
        "        curr_x = curr_x - lr * grad",
        "        history_x.append(curr_x)",
        "        history_y.append(f(curr_x))",
        "        ",
        "    fig, ax = plt.subplots()",
        "    ax.plot(x_range, f(x_range), color='blue', lw=2, label='Cost Function')",
        "    ax.plot(history_x, history_y, 'ro-', label='GD Steps', markersize=6, alpha=0.8)",
        "    ax.scatter([curr_x], [f(curr_x)], color='yellow', s=150, zorder=5, edgecolor='black', label='Final Point')",
        "    ",
        "    ax.grid(True, linestyle='--', alpha=0.5)",
        "    ax.legend()",
        "    ax.set_title(f'Gradient Descent (Final x = {curr_x:.4f})')",
        "    plt.show()",
        "",
        "interact(simulate_gd,",
        "         func_type=widgets.Dropdown(options=['Convex (x^2)', 'Non-Convex (x^4 - 2x^2)'], value='Convex (x^2)', description='Function'),",
        "         start_x=widgets.FloatSlider(value=2.5, min=-3.0, max=3.0, step=0.1, description='Start x0'),",
        "         lr=widgets.FloatSlider(value=0.1, min=0.01, max=1.1, step=0.02, description='Learning Rate'),",
        "         steps=widgets.IntSlider(value=10, min=1, max=50, step=1, description='Steps'));"
    ]),
    markdown_cell([
        "## Section 3: 3D Optimization Landscapes",
        "",
        "In ML, models have thousands of parameters. Optimization happens in high-dimensional space.",
        "Here we visualize a 3D loss surface $f(x, y) = x^2 + 2y^2$. The gradient vector is:",
        "$$\\nabla f(x, y) = \\begin{pmatrix} \\frac{\\partial f}{\\partial x} \\\\ \\frac{\\partial f}{\\partial y} \\end{pmatrix} = \\begin{pmatrix} 2x \\\\ 4y \\end{pmatrix}$$",
        "The gradient always points in the direction of **steepest ascent** (upwards), so we move opposite to it."
    ]),
    code_cell([
        "from mpl_toolkits.mplot3d import Axes3D",
        "",
        "def cost_3d(x, y):",
        "    return x**2 + 2*y**2",
        "",
        "def plot_gd_3d(start_x, start_y, lr, steps):",
        "    # Run 3D GD",
        "    hx, hy = [start_x], [start_y]",
        "    hz = [cost_3d(start_x, start_y)]",
        "    ",
        "    cx, cy = start_x, start_y",
        "    for _ in range(steps):",
        "        gx = 2 * cx",
        "        gy = 4 * cy",
        "        cx = cx - lr * gx",
        "        cy = cy - lr * gy",
        "        hx.append(cx)",
        "        hy.append(cy)",
        "        hz.append(cost_3d(cx, cy))",
        "        ",
        "    fig = plt.figure(figsize=(10, 7))",
        "    ax = fig.add_subplot(111, projection='3d')",
        "    ",
        "    # Create Surface",
        "    X = np.linspace(-3, 3, 50)",
        "    Y = np.linspace(-3, 3, 50)",
        "    X, Y = np.meshgrid(X, Y)",
        "    Z = cost_3d(X, Y)",
        "    ",
        "    ax.plot_surface(X, Y, Z, cmap='viridis', alpha=0.5, edgecolor='none')",
        "    ax.plot(hx, hy, hz, 'ro-', lw=2, markersize=5, label='GD Path', zorder=10)",
        "    ",
        "    ax.set_xlabel('Parameter X')",
        "    ax.set_ylabel('Parameter Y')",
        "    ax.set_zlabel('Loss / Cost')",
        "    ax.set_title('3D Gradient Descent Landscape')",
        "    ax.legend()",
        "    plt.show()",
        "",
        "interact(plot_gd_3d,",
        "         start_x=widgets.FloatSlider(value=2.5, min=-3.0, max=3.0, step=0.1, description='Start X'),",
        "         start_y=widgets.FloatSlider(value=2.5, min=-3.0, max=3.0, step=0.1, description='Start Y'),",
        "         lr=widgets.FloatSlider(value=0.1, min=0.01, max=0.6, step=0.02, description='Learning Rate'),",
        "         steps=widgets.IntSlider(value=10, min=1, max=40, step=1, description='Steps'));"
    ])
]

# ----------------- Notebook 3: Probability & Statistics -----------------
prob_cells = [
    markdown_cell([
        "# ML Mathematics Playground: 03. Probability & Statistics",
        "",
        "AI systems are probabilistic at heart. They predict probabilities of categories (e.g., Cat vs Dog) or estimate uncertainty.",
        "",
        "In this notebook, we will explore:",
        "1. **Gaussian/Normal Distribution**: The core probability distribution in nature.",
        "2. **Bayes' Theorem & Classifier**: Making decisions using likelihoods and prior beliefs."
    ]),
    code_cell([
        "%matplotlib inline",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "import scipy.stats as stats",
        "import ipywidgets as widgets",
        "from ipywidgets import interact, interactive",
        "",
        "plt.style.use('ggplot')",
        "plt.rcParams['figure.figsize'] = (8, 5)"
    ]),
    markdown_cell([
        "## Section 1: The Gaussian Distribution Playground",
        "",
        "The Normal Distribution is defined by:",
        "$$P(x) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{1}{2}\\left(\\frac{x-\\mu}{\\sigma}\\right)^2}$$",
        "where $\\mu$ is the **mean** (center) and $\\sigma$ is the **standard deviation** (width/spread).",
        "",
        "Use the sliders to adjust $\\mu$ and $\\sigma$ and see how the probability curve updates."
    ]),
    code_cell([
        "def plot_gaussian(mu, sigma):",
        "    x = np.linspace(-10, 10, 500)",
        "    y = stats.norm.pdf(x, mu, sigma)",
        "    ",
        "    fig, ax = plt.subplots()",
        "    ax.plot(x, y, color='blue', lw=2, label=f'N(μ={mu}, σ={sigma})')",
        "    ax.fill_between(x, y, color='blue', alpha=0.15)",
        "    ",
        "    # Annotate standard deviations",
        "    ax.axvline(mu, color='red', linestyle='--', alpha=0.7, label='Mean (μ)')",
        "    ax.axvline(mu + sigma, color='orange', linestyle=':', alpha=0.7, label='μ ± σ')",
        "    ax.axvline(mu - sigma, color='orange', linestyle=':', alpha=0.7)",
        "    ",
        "    ax.set_ylim(0, 1.0)",
        "    ax.grid(True, linestyle='--', alpha=0.5)",
        "    ax.legend(loc='upper right')",
        "    ax.set_title('Gaussian Probability Density Function')",
        "    plt.show()",
        "",
        "interact(plot_gaussian,",
        "         mu=widgets.FloatSlider(value=0.0, min=-5.0, max=5.0, step=0.1, description='Mean (μ)'),",
        "         sigma=widgets.FloatSlider(value=1.5, min=0.2, max=4.0, step=0.1, description='Std Dev (σ)'));"
    ]),
    markdown_cell([
        "## Section 2: Bayes' Theorem & Classifier",
        "",
        "Bayes' Theorem updates the probability of a hypothesis (class $C$) given evidence (feature $x$):",
        "$$P(C|x) = \\frac{P(x|C) \\cdot P(C)}{P(x)}$$",
        "- $P(C|x)$ is the **Posterior** probability.",
        "- $P(x|C)$ is the **Likelihood** of the feature given the class (often modeled as a Gaussian).",
        "- $P(C)$ is the **Prior** (probability of the class before seeing any data).",
        "",
        "Let's build a binary classifier to classify pets as **Cats** or **Dogs** based on their weight.",
        "- Cats: Mean weight $\\approx 4$ kg",
        "- Dogs: Mean weight $\\approx 12$ kg",
        "",
        "Adjust the **Prior Probability of Dog** $P(\\text{Dog})$ to see how our classification boundary moves. If dogs are extremely rare (low prior), the classifier requires much stronger weight evidence to classify a pet as a dog!"
    ]),
    code_cell([
        "def plot_bayes_classifier(prior_dog, cat_mu, cat_sigma, dog_mu, dog_sigma):",
        "    prior_cat = 1.0 - prior_dog",
        "    ",
        "    weights = np.linspace(0, 20, 500)",
        "    ",
        "    # Likelihoods P(weight | Class)",
        "    likelihood_cat = stats.norm.pdf(weights, cat_mu, cat_sigma)",
        "    likelihood_dog = stats.norm.pdf(weights, dog_mu, dog_sigma)",
        "    ",
        "    # Unnormalized Posteriors: Likelihood * Prior",
        "    post_cat = likelihood_cat * prior_cat",
        "    post_dog = likelihood_dog * prior_dog",
        "    ",
        "    # Total probability P(weight)",
        "    evidence = post_cat + post_dog",
        "    ",
        "    # Normalized Posteriors",
        "    posterior_cat = post_cat / (evidence + 1e-9)",
        "    posterior_dog = post_dog / (evidence + 1e-9)",
        "    ",
        "    # Find decision boundary (where P(Dog|x) = P(Cat|x) = 0.5)",
        "    diff = np.abs(posterior_dog - 0.5)",
        "    boundary_idx = np.argmin(diff)",
        "    boundary_val = weights[boundary_idx]",
        "    ",
        "    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 8), sharex=True)",
        "    ",
        "    # Plot Likelihoods",
        "    ax1.plot(weights, likelihood_cat, color='green', lw=2, label='Cat Likelihood P(weight|Cat)')",
        "    ax1.plot(weights, likelihood_dog, color='blue', lw=2, label='Dog Likelihood P(weight|Dog)')",
        "    ax1.fill_between(weights, likelihood_cat, color='green', alpha=0.1)",
        "    ax1.fill_between(weights, likelihood_dog, color='blue', alpha=0.1)",
        "    ax1.set_ylabel('Probability Density')",
        "    ax1.set_title('Likelihoods (Class-Conditional Distributions)')",
        "    ax1.legend(loc='upper right')",
        "    ",
        "    # Plot Posteriors",
        "    ax2.plot(weights, posterior_cat, color='green', lw=2, label='Posterior P(Cat|weight)')",
        "    ax2.plot(weights, posterior_dog, color='blue', lw=2, label='Posterior P(Dog|weight)')",
        "    ax2.axvline(boundary_val, color='red', linestyle='--', lw=2, label=f'Decision Boundary: {boundary_val:.2f} kg')",
        "    ax2.set_xlabel('Weight (kg)')",
        "    ax2.set_ylabel('Posterior Probability')",
        "    ax2.set_title('Posteriors (Calculated via Bayes Rule)')",
        "    ax2.legend(loc='upper right')",
        "    ",
        "    plt.tight_layout()",
        "    plt.show()",
        "",
        "interact(plot_bayes_classifier,",
        "         prior_dog=widgets.FloatSlider(value=0.5, min=0.01, max=0.99, step=0.05, description='P(Dog) Prior'),",
        "         cat_mu=widgets.FloatSlider(value=4.0, min=2.0, max=8.0, step=0.5, description='Cat Mean Weight'),",
        "         cat_sigma=widgets.FloatSlider(value=1.5, min=0.5, max=3.0, step=0.1, description='Cat Std Dev'),",
        "         dog_mu=widgets.FloatSlider(value=12.0, min=8.0, max=16.0, step=0.5, description='Dog Mean Weight'),",
        "         dog_sigma=widgets.FloatSlider(value=2.5, min=0.5, max=4.0, step=0.1, description='Dog Std Dev'));"
    ])
]

# Write out files
create_notebook("01_linear_algebra.ipynb", la_cells)
create_notebook("02_calculus_optimization.ipynb", calc_cells)
create_notebook("03_probability_statistics.ipynb", prob_cells)

# Step 29
